### ISSUE TITLE
btrfscue: no device file given, only inline file data will be visible

### ISSUE THREAD

**Issue by AngelDCode** [cblichmann/btrfscue#8]
btrfscue: no device file given, only inline file data will be visible

I type the command: `btrfscue --metadata <metadata.db> mount <mountpoint>`

How I can specify the device file, for read the file data?

**Comment by cblichmann** [comment]
The correct syntax with a device file is this:
    `btrfscue --metadata <metadata.db> mount <device_file> <mountpoint>`

The command-line interface leaves much to be desired in this state, sorry :)
